"""crear tablas iniciales

Revision ID: 8e6a822dc9ab
Revises: 
Create Date: 2026-09-26 18:12:37.560144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6a822dc9ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ligas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_liga', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ligas_id'), 'ligas', ['id'], unique=False)
    op.create_index(op.f('ix_ligas_nombre_liga'), 'ligas', ['nombre_liga'], unique=False)
    op.create_index(op.f('ix_ligas_pais'), 'ligas', ['pais'], unique=True)
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sa.String(), nullable=True),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('encargado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encargado_id'], ['ligas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.create_index(op.f('ix_equipos_nombre_equipo'), 'equipos', ['nombre_equipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipos_nombre_equipo'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_ligas_pais'), table_name='ligas')
    op.drop_index(op.f('ix_ligas_nombre_liga'), table_name='ligas')
    op.drop_index(op.f('ix_ligas_id'), table_name='ligas')
    op.drop_table('ligas')
    # ### end Alembic commands ###
