"""Character limit in inputs

Revision ID: f50207ab300e
Revises: 2175bece0825
Create Date: 2026-09-29 20:47:01.695391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50207ab300e'
down_revision: Union[str, Sequence[str], None] = '2175bece0825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leagues_country'), table_name='leagues')
    op.create_index(op.f('ix_leagues_country'), 'leagues', ['country'], unique=False)
    op.drop_index(op.f('ix_leagues_league_name'), table_name='leagues')
    op.create_index(op.f('ix_leagues_league_name'), 'leagues', ['league_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leagues_league_name'), table_name='leagues')
    op.create_index(op.f('ix_leagues_league_name'), 'leagues', ['league_name'], unique=False)
    op.drop_index(op.f('ix_leagues_country'), table_name='leagues')
    op.create_index(op.f('ix_leagues_country'), 'leagues', ['country'], unique=1)
    # ### end Alembic commands ###
